# Generated by Django 3.0.5 on 2021-12-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
